// <auto-generated />
namespace Exam_Product.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class eight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eight));
        
        string IMigrationMetadata.Id
        {
            get { return "202103111630307_eight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
